#this is done via route annotations now
#user_show:
#   pattern:  /{id}/show
#  defaults: { _controller: "UserBundle:user:show" }

user_new:
    pattern:  /admin/new
    defaults: { _controller: "UserBundle:User:new" }


user_new_admin:
    pattern:  /admin/admin_new
    defaults: { _controller: "UserBundle:User:new" }


user_create:
    pattern:  /create
    defaults: { _controller: "UserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UserBundle:EditUser:edit" }

user_update:
    pattern:  /admin/update/{id}
    defaults: { _controller: "UserBundle:EditUser:update" }


user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    requirements: { _method: post|delete }
