SymfonyGallery\AdminCoreBundle\Entity\Category:
    type: entity
    table: null
    table: category
    readOnly: false
    indexes:
        name_index:
            columns: [ category_name ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        categoryName:
            type: string
            length: '50'
            column: category_name
        folderId:
            type: integer
            column: folder_id
        date:
            type: date
            column: date

