category_controller:
    pattern: /category
    defaults: { _controller: "AdminCoreBundle:Category:index" }

category_show:
    pattern: /category/show/{id}
    defaults: { _controller: "AdminCoreBundle:Category:show" }